// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using GncOmsApi.Models;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Data;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CanalPedido> CanalPedido { get; set; }

    public virtual DbSet<CanalVenta> CanalVenta { get; set; }

    public virtual DbSet<CarrierAsignado> CarrierAsignado { get; set; }

    public virtual DbSet<CarrierCatalogo> CarrierCatalogo { get; set; }

    public virtual DbSet<CarrierSla> CarrierSla { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<ConfiguracionGeneral> ConfiguracionGeneral { get; set; }

    public virtual DbSet<ConfirmacionPago> ConfirmacionPago { get; set; }

    public virtual DbSet<Devolucion> Devolucion { get; set; }

    public virtual DbSet<DireccionEnvio> DireccionEnvio { get; set; }

    public virtual DbSet<EstatusPedido> EstatusPedido { get; set; }

    public virtual DbSet<HistoricoEstatusPedido> HistoricoEstatusPedido { get; set; }

    public virtual DbSet<HistoricoSendEmail> HistoricoSendEmail { get; set; }

    public virtual DbSet<HistoricoTrackingEnvio> HistoricoTrackingEnvio { get; set; }

    public virtual DbSet<IntegrationAlerts> IntegrationAlerts { get; set; }

    public virtual DbSet<MotivoDevolucion> MotivoDevolucion { get; set; }

    public virtual DbSet<OutboxConsumerCheckpoint> OutboxConsumerCheckpoint { get; set; }

    public virtual DbSet<OutboxConsumerFailures> OutboxConsumerFailures { get; set; }

    public virtual DbSet<OutboxEvents> OutboxEvents { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<PedidoDetalle> PedidoDetalle { get; set; }

    public virtual DbSet<TipoServicio> TipoServicio { get; set; }

    public virtual DbSet<TransicionEstatusConfig> TransicionEstatusConfig { get; set; }

    public virtual DbSet<WebhookEventsLog> WebhookEventsLog { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CanalPedido>(entity =>
        {
            entity.HasIndex(e => e.IdExterno, "IX_CanalPedido_id_externo").HasFilter("([id_externo] IS NOT NULL)");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_CanalPedido_id");

            entity.HasOne(d => d.CanalVenta).WithMany(p => p.CanalPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CanalPedido_CanalVenta");

            entity.HasOne(d => d.Pedido).WithMany(p => p.CanalPedido).HasConstraintName("FK_CanalPedido_Pedido");
        });

        modelBuilder.Entity<CanalVenta>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_CanalVenta_id");
            entity.Property(e => e.Activo).HasDefaultValue(true, "DF_CanalVenta_activo");
        });

        modelBuilder.Entity<CarrierAsignado>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_CarrierAsignado_id");
            entity.Property(e => e.FechaAsignacion).HasDefaultValueSql("(sysutcdatetime())", "DF_CarrierAsignado_fecha_asig");

            entity.HasOne(d => d.Carrier).WithMany(p => p.CarrierAsignado)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarrierAsignado_CarrierCatalogo");

            entity.HasOne(d => d.Pedido).WithMany(p => p.CarrierAsignado).HasConstraintName("FK_CarrierAsignado_Pedido");
        });

        modelBuilder.Entity<CarrierCatalogo>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_CarrierCatalogo_id");
            entity.Property(e => e.Activo).HasDefaultValue(true, "DF_CarrierCatalogo_activo");
        });

        modelBuilder.Entity<CarrierSla>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_CarrierSLA_id");
            entity.Property(e => e.Activo).HasDefaultValue(true, "DF_CarrierSLA_activo");

            entity.HasOne(d => d.Carrier).WithMany(p => p.CarrierSla)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarrierSLA_CarrierCatalogo");

            entity.HasOne(d => d.TipoServicio).WithMany(p => p.CarrierSla)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CarrierSLA_TipoServicio");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.Property(e => e.ClienteId).HasDefaultValueSql("(newid())", "DF_Cliente_cliente_id");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())", "DF_Cliente_fecha_creacion");
        });

        modelBuilder.Entity<ConfiguracionGeneral>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_ConfiguracionGeneral_id");
            entity.Property(e => e.FechaActualizacion).HasDefaultValueSql("(sysutcdatetime())", "DF_ConfiguracionGeneral_fecha");
        });

        modelBuilder.Entity<ConfirmacionPago>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_ConfirmacionPago_id");

            entity.HasOne(d => d.Pedido).WithMany(p => p.ConfirmacionPago).HasConstraintName("FK_ConfirmacionPago_Pedido");
        });

        modelBuilder.Entity<Devolucion>(entity =>
        {
            entity.Property(e => e.DevolucionId).HasDefaultValueSql("(newid())", "DF_Devolucion_id");
            entity.Property(e => e.FechaSolicitud).HasDefaultValueSql("(sysutcdatetime())", "DF_Devolucion_fecha_solicitud");

            entity.HasOne(d => d.Motivo).WithMany(p => p.Devolucion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Devolucion_MotivoDevolucion");

            entity.HasOne(d => d.Pedido).WithMany(p => p.Devolucion).HasConstraintName("FK_Devolucion_Pedido");
        });

        modelBuilder.Entity<DireccionEnvio>(entity =>
        {
            entity.Property(e => e.DireccionId).HasDefaultValueSql("(newid())", "DF_DireccionEnvio_id");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())", "DF_DireccionEnvio_fecha");
            entity.Property(e => e.Pais).HasDefaultValue("MX", "DF_DireccionEnvio_pais");

            entity.HasOne(d => d.Cliente).WithMany(p => p.DireccionEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DireccionEnvio_Cliente");
        });

        modelBuilder.Entity<EstatusPedido>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_EstatusPedido_id");
        });

        modelBuilder.Entity<HistoricoEstatusPedido>(entity =>
        {
            entity.Property(e => e.Timestamp).HasDefaultValueSql("(sysutcdatetime())", "DF_HistoricoEstatusPedido_timestamp");

            entity.HasOne(d => d.EstatusAnterior).WithMany(p => p.HistoricoEstatusPedidoEstatusAnterior).HasConstraintName("FK_HistoricoEstatusPedido_EstatusAnterior");

            entity.HasOne(d => d.EstatusNuevo).WithMany(p => p.HistoricoEstatusPedidoEstatusNuevo)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HistoricoEstatusPedido_EstatusNuevo");

            entity.HasOne(d => d.Pedido).WithMany(p => p.HistoricoEstatusPedido).HasConstraintName("FK_HistoricoEstatusPedido_Pedido");
        });

        modelBuilder.Entity<HistoricoSendEmail>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_HistoricoSendEmail_id");
            entity.Property(e => e.FechaEnvio).HasDefaultValueSql("(sysutcdatetime())", "DF_HistoricoSendEmail_fecha");

            entity.HasOne(d => d.Pedido).WithMany(p => p.HistoricoSendEmail).HasConstraintName("FK_HistoricoSendEmail_Pedido");
        });

        modelBuilder.Entity<HistoricoTrackingEnvio>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_HistoricoTrackingEnvio_id");
            entity.Property(e => e.FechaRegistro).HasDefaultValueSql("(sysutcdatetime())", "DF_HistoricoTrackingEnvio_registro");

            entity.HasOne(d => d.CarrierAsignado).WithMany(p => p.HistoricoTrackingEnvio)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HistoricoTrackingEnvio_CarrierAsignado");

            entity.HasOne(d => d.Pedido).WithMany(p => p.HistoricoTrackingEnvio).HasConstraintName("FK_HistoricoTrackingEnvio_Pedido");
        });

        modelBuilder.Entity<IntegrationAlerts>(entity =>
        {
            entity.HasIndex(e => e.Resuelto, "IX_integration_alerts_resuelto").HasFilter("([resuelto]=(0))");

            entity.Property(e => e.AlertId).HasDefaultValueSql("(newid())", "DF_integration_alerts_id");
            entity.Property(e => e.CreadoEn).HasDefaultValueSql("(sysutcdatetime())", "DF_integration_alerts_creado");

            entity.HasOne(d => d.Pedido).WithMany(p => p.IntegrationAlerts).HasConstraintName("FK_integration_alerts_Pedido");
        });

        modelBuilder.Entity<MotivoDevolucion>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_MotivoDevolucion_id");
        });

        modelBuilder.Entity<OutboxConsumerCheckpoint>(entity =>
        {
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_outbox_consumer_checkpoint_updated");
        });

        modelBuilder.Entity<OutboxConsumerFailures>(entity =>
        {
            entity.Property(e => e.UltimoIntentoEn).HasDefaultValueSql("(sysutcdatetime())", "DF_outbox_consumer_failures_ultimo");

            entity.HasOne(d => d.Event).WithMany(p => p.OutboxConsumerFailures).HasConstraintName("FK_outbox_consumer_failures_outbox_events");
        });

        modelBuilder.Entity<OutboxEvents>(entity =>
        {
            entity.Property(e => e.EventId).HasDefaultValueSql("(newid())", "DF_outbox_events_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_outbox_events_created");
            entity.Property(e => e.Seq).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Pedido).WithMany(p => p.OutboxEvents).HasConstraintName("FK_outbox_events_Pedido");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasIndex(e => e.CarrierFinalId, "IX_Pedido_carrier_final_id").HasFilter("([carrier_final_id] IS NOT NULL)");

            entity.HasIndex(e => e.TiendaAsignadaId, "IX_Pedido_tienda_asignada_id").HasFilter("([tienda_asignada_id] IS NOT NULL)");

            entity.Property(e => e.PedidoId).HasDefaultValueSql("(newid())", "DF_Pedido_pedido_id");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(sysutcdatetime())", "DF_Pedido_fecha_creacion");
            entity.Property(e => e.FechaUltimaActualizacion).HasDefaultValueSql("(sysutcdatetime())", "DF_Pedido_fecha_act");

            entity.HasOne(d => d.CanalVenta).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_CanalVenta");

            entity.HasOne(d => d.CarrierFinal).WithMany(p => p.Pedido).HasConstraintName("FK_Pedido_CarrierCatalogo");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_Cliente");

            entity.HasOne(d => d.DireccionEnvio).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_DireccionEnvio");

            entity.HasOne(d => d.EstatusActual).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_EstatusPedido");
        });

        modelBuilder.Entity<PedidoDetalle>(entity =>
        {
            entity.Property(e => e.DetalleId).HasDefaultValueSql("(newid())", "DF_PedidoDetalle_id");

            entity.HasOne(d => d.Pedido).WithMany(p => p.PedidoDetalle).HasConstraintName("FK_PedidoDetalle_Pedido");
        });

        modelBuilder.Entity<TipoServicio>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())", "DF_TipoServicio_id");
        });

        modelBuilder.Entity<TransicionEstatusConfig>(entity =>
        {
            entity.Property(e => e.Activo).HasDefaultValue(true, "DF_TransicionEstatusConfig_activo");

            entity.HasOne(d => d.EstatusDestino).WithMany(p => p.TransicionEstatusConfigEstatusDestino)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transicion_EstatusDestino");

            entity.HasOne(d => d.EstatusOrigen).WithMany(p => p.TransicionEstatusConfigEstatusOrigen)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Transicion_EstatusOrigen");
        });

        modelBuilder.Entity<WebhookEventsLog>(entity =>
        {
            entity.HasIndex(e => e.Procesado, "IX_webhook_events_log_procesado").HasFilter("([procesado]=(0))");

            entity.Property(e => e.ReceivedAt).HasDefaultValueSql("(sysutcdatetime())", "DF_webhook_events_log_received");

            entity.HasOne(d => d.Carrier).WithMany(p => p.WebhookEventsLog)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_webhook_events_log_CarrierCatalogo");

            entity.HasOne(d => d.Pedido).WithMany(p => p.WebhookEventsLog).HasConstraintName("FK_webhook_events_log_Pedido");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}