// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("PedidoId", Name = "IX_CanalPedido_pedido_id")]
public partial class CanalPedido
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("canal_venta_id")]
    public Guid CanalVentaId { get; set; }

    [Column("id_externo")]
    [StringLength(100)]
    public string IdExterno { get; set; }

    [Column("tracking_url")]
    [StringLength(255)]
    public string TrackingUrl { get; set; }

    [Column("handoff_code")]
    [StringLength(100)]
    public string HandoffCode { get; set; }

    [Column("metadata_json")]
    public string MetadataJson { get; set; }

    [ForeignKey("CanalVentaId")]
    [InverseProperty("CanalPedido")]
    public virtual CanalVenta CanalVenta { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("CanalPedido")]
    public virtual Pedido Pedido { get; set; }
}