// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("Codigo", Name = "UQ_CanalVenta_codigo", IsUnique = true)]
public partial class CanalVenta
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("codigo")]
    [StringLength(50)]
    public string Codigo { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Column("activo")]
    public bool Activo { get; set; }

    [InverseProperty("CanalVenta")]
    public virtual ICollection<CanalPedido> CanalPedido { get; set; } = new List<CanalPedido>();

    [InverseProperty("CanalVenta")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}