// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("CarrierSLA")]
[Index("CarrierId", Name = "IX_CarrierSLA_carrier_id")]
[Index("TipoServicioId", Name = "IX_CarrierSLA_tipo_servicio_id")]
public partial class CarrierSla
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("carrier_id")]
    public Guid CarrierId { get; set; }

    [Column("tipo_servicio_id")]
    public Guid TipoServicioId { get; set; }

    [Column("valor_pickup")]
    public int ValorPickup { get; set; }

    [Column("descripcion_pickup")]
    [StringLength(100)]
    public string DescripcionPickup { get; set; }

    [Column("valor_sla")]
    public int ValorSla { get; set; }

    [Column("descripcion_sla")]
    [StringLength(100)]
    public string DescripcionSla { get; set; }

    [Column("activo")]
    public bool Activo { get; set; }

    [ForeignKey("CarrierId")]
    [InverseProperty("CarrierSla")]
    public virtual CarrierCatalogo Carrier { get; set; }

    [ForeignKey("TipoServicioId")]
    [InverseProperty("CarrierSla")]
    public virtual TipoServicio TipoServicio { get; set; }
}