// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("CarrierId", Name = "IX_CarrierAsignado_carrier_id")]
[Index("NumeroGuia", Name = "IX_CarrierAsignado_numero_guia")]
[Index("PedidoId", Name = "IX_CarrierAsignado_pedido_id")]
public partial class CarrierAsignado
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("carrier_id")]
    public Guid CarrierId { get; set; }

    [Required]
    [Column("fuente_sistema")]
    [StringLength(50)]
    public string FuenteSistema { get; set; }

    [Required]
    [Column("numero_guia")]
    [StringLength(100)]
    public string NumeroGuia { get; set; }

    [Required]
    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("fecha_asignacion")]
    public DateTime FechaAsignacion { get; set; }

    [Column("fecha_entrega_estimada")]
    public DateTime? FechaEntregaEstimada { get; set; }

    [Column("fecha_entrega_real")]
    public DateTime? FechaEntregaReal { get; set; }

    [ForeignKey("CarrierId")]
    [InverseProperty("CarrierAsignado")]
    public virtual CarrierCatalogo Carrier { get; set; }

    [InverseProperty("CarrierAsignado")]
    public virtual ICollection<HistoricoTrackingEnvio> HistoricoTrackingEnvio { get; set; } = new List<HistoricoTrackingEnvio>();

    [ForeignKey("PedidoId")]
    [InverseProperty("CarrierAsignado")]
    public virtual Pedido Pedido { get; set; }
}