// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("ExternalCarrierId", Name = "UQ_CarrierCatalogo_external_carrier_id", IsUnique = true)]
public partial class CarrierCatalogo
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("external_carrier_id")]
    [StringLength(50)]
    public string ExternalCarrierId { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [Column("metodo_tracking")]
    [StringLength(20)]
    public string MetodoTracking { get; set; }

    [Column("api_endpoint")]
    [StringLength(255)]
    public string ApiEndpoint { get; set; }

    [Column("activo")]
    public bool Activo { get; set; }

    [InverseProperty("Carrier")]
    public virtual ICollection<CarrierAsignado> CarrierAsignado { get; set; } = new List<CarrierAsignado>();

    [InverseProperty("Carrier")]
    public virtual ICollection<CarrierSla> CarrierSla { get; set; } = new List<CarrierSla>();

    [InverseProperty("CarrierFinal")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();

    [InverseProperty("Carrier")]
    public virtual ICollection<WebhookEventsLog> WebhookEventsLog { get; set; } = new List<WebhookEventsLog>();
}