// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

public partial class Cliente
{
    [Key]
    [Column("cliente_id")]
    public Guid ClienteId { get; set; }

    [Required]
    [Column("external_destination_id")]
    [StringLength(100)]
    public string ExternalDestinationId { get; set; }

    [Column("customer_external_id")]
    public long? CustomerExternalId { get; set; }

    [Required]
    [Column("nombre")]
    [StringLength(100)]
    public string Nombre { get; set; }

    [Required]
    [Column("apellido")]
    [StringLength(100)]
    public string Apellido { get; set; }

    [Column("telefono")]
    [StringLength(20)]
    public string Telefono { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Column("fecha_creacion")]
    public DateTime FechaCreacion { get; set; }

    [InverseProperty("Cliente")]
    public virtual ICollection<DireccionEnvio> DireccionEnvio { get; set; } = new List<DireccionEnvio>();

    [InverseProperty("Cliente")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}