// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("Enviado", "Confirmado", Name = "IX_ConfirmacionPago_enviado_confirmado")]
[Index("PedidoId", Name = "IX_ConfirmacionPago_pedido_id")]
public partial class ConfirmacionPago
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Required]
    [Column("metodo_pago")]
    [StringLength(50)]
    public string MetodoPago { get; set; }

    [Column("auth_code")]
    [StringLength(100)]
    public string AuthCode { get; set; }

    [Column("monto", TypeName = "decimal(18, 2)")]
    public decimal Monto { get; set; }

    [Column("enviado")]
    public bool Enviado { get; set; }

    [Column("confirmado")]
    public bool Confirmado { get; set; }

    [Column("fecha_envio")]
    public DateTime? FechaEnvio { get; set; }

    [Column("fecha_confirmacion")]
    public DateTime? FechaConfirmacion { get; set; }

    [Column("intentos")]
    public int Intentos { get; set; }

    [Column("ultimo_error")]
    public string UltimoError { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("ConfirmacionPago")]
    public virtual Pedido Pedido { get; set; }
}