// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("Clave", Name = "UQ_ConfiguracionGeneral_clave", IsUnique = true)]
public partial class ConfiguracionGeneral
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("clave")]
    [StringLength(100)]
    public string Clave { get; set; }

    [Required]
    [Column("valor")]
    public string Valor { get; set; }

    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [Column("fecha_actualizacion")]
    public DateTime FechaActualizacion { get; set; }
}