// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("MotivoId", Name = "IX_Devolucion_motivo_id")]
[Index("PedidoId", Name = "IX_Devolucion_pedido_id")]
public partial class Devolucion
{
    [Key]
    [Column("devolucion_id")]
    public Guid DevolucionId { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("motivo_id")]
    public Guid MotivoId { get; set; }

    [Column("ticket_id")]
    [StringLength(100)]
    public string TicketId { get; set; }

    [Required]
    [Column("metodo")]
    [StringLength(50)]
    public string Metodo { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(50)]
    public string Estado { get; set; }

    [Column("fecha_solicitud")]
    public DateTime FechaSolicitud { get; set; }

    [Column("fecha_recepcion")]
    public DateTime? FechaRecepcion { get; set; }

    [Column("usuario_proceso_id")]
    [StringLength(100)]
    public string UsuarioProcesoId { get; set; }

    [Column("usuario_proceso_nombre")]
    [StringLength(100)]
    public string UsuarioProcesoNombre { get; set; }

    [ForeignKey("MotivoId")]
    [InverseProperty("Devolucion")]
    public virtual MotivoDevolucion Motivo { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("Devolucion")]
    public virtual Pedido Pedido { get; set; }
}