// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("ClienteId", Name = "IX_DireccionEnvio_cliente_id")]
public partial class DireccionEnvio
{
    [Key]
    [Column("direccion_id")]
    public Guid DireccionId { get; set; }

    [Column("cliente_id")]
    public Guid ClienteId { get; set; }

    [Required]
    [Column("address1")]
    [StringLength(255)]
    public string Address1 { get; set; }

    [Column("address2")]
    [StringLength(255)]
    public string Address2 { get; set; }

    [Required]
    [Column("ciudad")]
    [StringLength(100)]
    public string Ciudad { get; set; }

    [Required]
    [Column("estado")]
    [StringLength(100)]
    public string Estado { get; set; }

    [Required]
    [Column("codigo_postal")]
    [StringLength(20)]
    public string CodigoPostal { get; set; }

    [Required]
    [Column("pais")]
    [StringLength(100)]
    public string Pais { get; set; }

    [Column("referencia")]
    [StringLength(255)]
    public string Referencia { get; set; }

    [Column("latitud")]
    public double? Latitud { get; set; }

    [Column("longitud")]
    public double? Longitud { get; set; }

    [Column("fecha_creacion")]
    public DateTime FechaCreacion { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("DireccionEnvio")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("DireccionEnvio")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}