// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("Codigo", Name = "UQ_EstatusPedido_codigo", IsUnique = true)]
public partial class EstatusPedido
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("codigo")]
    [StringLength(50)]
    public string Codigo { get; set; }

    [Required]
    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [InverseProperty("EstatusAnterior")]
    public virtual ICollection<HistoricoEstatusPedido> HistoricoEstatusPedidoEstatusAnterior { get; set; } = new List<HistoricoEstatusPedido>();

    [InverseProperty("EstatusNuevo")]
    public virtual ICollection<HistoricoEstatusPedido> HistoricoEstatusPedidoEstatusNuevo { get; set; } = new List<HistoricoEstatusPedido>();

    [InverseProperty("EstatusActual")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();

    [InverseProperty("EstatusDestino")]
    public virtual ICollection<TransicionEstatusConfig> TransicionEstatusConfigEstatusDestino { get; set; } = new List<TransicionEstatusConfig>();

    [InverseProperty("EstatusOrigen")]
    public virtual ICollection<TransicionEstatusConfig> TransicionEstatusConfigEstatusOrigen { get; set; } = new List<TransicionEstatusConfig>();
}