// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("PedidoId", Name = "IX_HistoricoSendEmail_pedido_id")]
public partial class HistoricoSendEmail
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Required]
    [Column("tipo_email")]
    [StringLength(50)]
    public string TipoEmail { get; set; }

    [Required]
    [Column("destinatario")]
    [StringLength(255)]
    public string Destinatario { get; set; }

    [Column("fecha_envio")]
    public DateTime FechaEnvio { get; set; }

    [Required]
    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("HistoricoSendEmail")]
    public virtual Pedido Pedido { get; set; }
}