// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("PedidoId", Name = "IX_HistoricoEstatusPedido_pedido_id")]
[Index("Timestamp", Name = "IX_HistoricoEstatusPedido_timestamp", AllDescending = true)]
public partial class HistoricoEstatusPedido
{
    [Key]
    [Column("history_id")]
    public long HistoryId { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("estatus_anterior_id")]
    public Guid? EstatusAnteriorId { get; set; }

    [Column("estatus_nuevo_id")]
    public Guid EstatusNuevoId { get; set; }

    [Required]
    [Column("origen")]
    [StringLength(100)]
    public string Origen { get; set; }

    [Column("timestamp")]
    public DateTime Timestamp { get; set; }

    [Column("metadata_json")]
    public string MetadataJson { get; set; }

    [ForeignKey("EstatusAnteriorId")]
    [InverseProperty("HistoricoEstatusPedidoEstatusAnterior")]
    public virtual EstatusPedido EstatusAnterior { get; set; }

    [ForeignKey("EstatusNuevoId")]
    [InverseProperty("HistoricoEstatusPedidoEstatusNuevo")]
    public virtual EstatusPedido EstatusNuevo { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("HistoricoEstatusPedido")]
    public virtual Pedido Pedido { get; set; }
}