// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("CarrierAsignadoId", Name = "IX_HistoricoTrackingEnvio_carrier_asignado_id")]
[Index("PedidoId", Name = "IX_HistoricoTrackingEnvio_pedido_id")]
public partial class HistoricoTrackingEnvio
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("carrier_asignado_id")]
    public Guid CarrierAsignadoId { get; set; }

    [Required]
    [Column("fuente_sistema")]
    [StringLength(50)]
    public string FuenteSistema { get; set; }

    [Required]
    [Column("estatus_tracking")]
    [StringLength(50)]
    public string EstatusTracking { get; set; }

    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [Column("ubicacion")]
    [StringLength(100)]
    public string Ubicacion { get; set; }

    [Column("fecha_evento")]
    public DateTime FechaEvento { get; set; }

    [Column("fecha_registro")]
    public DateTime FechaRegistro { get; set; }

    [ForeignKey("CarrierAsignadoId")]
    [InverseProperty("HistoricoTrackingEnvio")]
    public virtual CarrierAsignado CarrierAsignado { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("HistoricoTrackingEnvio")]
    public virtual Pedido Pedido { get; set; }
}