// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("integration_alerts")]
[Index("PedidoId", Name = "IX_integration_alerts_pedido_id")]
public partial class IntegrationAlerts
{
    [Key]
    [Column("alert_id")]
    public Guid AlertId { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(50)]
    public string Tipo { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("detalle")]
    public string Detalle { get; set; }

    [Column("creado_en")]
    public DateTime CreadoEn { get; set; }

    [Column("resuelto")]
    public bool Resuelto { get; set; }

    [Column("resuelto_en")]
    public DateTime? ResueltoEn { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("IntegrationAlerts")]
    public virtual Pedido Pedido { get; set; }
}