// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

public partial class MotivoDevolucion
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("motivo")]
    [StringLength(100)]
    public string Motivo { get; set; }

    [Required]
    [Column("descripcion")]
    [StringLength(255)]
    public string Descripcion { get; set; }

    [InverseProperty("Motivo")]
    public virtual ICollection<Devolucion> Devolucion { get; set; } = new List<Devolucion>();
}