// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("outbox_events")]
[Index("PedidoId", Name = "IX_outbox_events_pedido_id")]
[Index("Status", "CreatedAt", Name = "IX_outbox_events_status_created")]
public partial class OutboxEvents
{
    [Key]
    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("seq")]
    public long Seq { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Required]
    [Column("event_type")]
    [StringLength(100)]
    public string EventType { get; set; }

    [Required]
    [Column("payload")]
    public string Payload { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("published_at")]
    public DateTime? PublishedAt { get; set; }

    [Required]
    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<OutboxConsumerFailures> OutboxConsumerFailures { get; set; } = new List<OutboxConsumerFailures>();

    [ForeignKey("PedidoId")]
    [InverseProperty("OutboxEvents")]
    public virtual Pedido Pedido { get; set; }
}