// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("outbox_consumer_failures")]
[Index("EventId", Name = "IX_outbox_consumer_failures_event_id")]
public partial class OutboxConsumerFailures
{
    [Key]
    [Column("failure_id")]
    public long FailureId { get; set; }

    [Required]
    [Column("consumer_name")]
    [StringLength(50)]
    public string ConsumerName { get; set; }

    [Column("event_id")]
    public Guid EventId { get; set; }

    [Column("intentos")]
    public int Intentos { get; set; }

    [Column("ultimo_error")]
    public string UltimoError { get; set; }

    [Column("ultimo_intento_en")]
    public DateTime UltimoIntentoEn { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("OutboxConsumerFailures")]
    public virtual OutboxEvents Event { get; set; }
}