// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("outbox_consumer_checkpoint")]
public partial class OutboxConsumerCheckpoint
{
    [Key]
    [Column("consumer_name")]
    [StringLength(50)]
    public string ConsumerName { get; set; }

    [Column("last_processed_seq")]
    public long LastProcessedSeq { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }
}