// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("PedidoId", Name = "IX_PedidoDetalle_pedido_id")]
[Index("Sku", Name = "IX_PedidoDetalle_sku")]
public partial class PedidoDetalle
{
    [Key]
    [Column("detalle_id")]
    public Guid DetalleId { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Required]
    [Column("sku")]
    [StringLength(50)]
    public string Sku { get; set; }

    [Column("cantidad")]
    public int Cantidad { get; set; }

    [Column("precio", TypeName = "decimal(18, 2)")]
    public decimal Precio { get; set; }

    [Column("impuesto", TypeName = "decimal(18, 2)")]
    public decimal Impuesto { get; set; }

    [Column("estado_reserva")]
    [StringLength(50)]
    public string EstadoReserva { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("PedidoDetalle")]
    public virtual Pedido Pedido { get; set; }
}