// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("CanalVentaId", Name = "IX_Pedido_canal_venta_id")]
[Index("ClienteId", Name = "IX_Pedido_cliente_id")]
[Index("EstatusActualId", Name = "IX_Pedido_estatus_actual_id")]
[Index("FechaCreacion", Name = "IX_Pedido_fecha_creacion", AllDescending = true)]
[Index("OrderNumber", Name = "UQ_Pedido_order_number", IsUnique = true)]
public partial class Pedido
{
    [Key]
    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("cliente_id")]
    public Guid ClienteId { get; set; }

    [Column("direccion_envio_id")]
    public Guid DireccionEnvioId { get; set; }

    [Column("canal_venta_id")]
    public Guid CanalVentaId { get; set; }

    [Column("estatus_actual_id")]
    public Guid EstatusActualId { get; set; }

    [Column("carrier_final_id")]
    public Guid? CarrierFinalId { get; set; }

    [Required]
    [Column("order_number")]
    [StringLength(100)]
    public string OrderNumber { get; set; }

    [Column("tipo_orden")]
    [StringLength(50)]
    public string TipoOrden { get; set; }

    [Column("tienda_asignada_id")]
    [StringLength(50)]
    public string TiendaAsignadaId { get; set; }

    [Column("tracking_id")]
    [StringLength(100)]
    public string TrackingId { get; set; }

    [Column("intentos_reroute")]
    public int IntentosReroute { get; set; }

    [Column("sync_irroute_confirmado")]
    public bool SyncIrrouteConfirmado { get; set; }

    [Column("sync_sa_confirmado")]
    public bool SyncSaConfirmado { get; set; }

    [Column("sync_merch_confirmado")]
    public bool SyncMerchConfirmado { get; set; }

    [Column("fecha_creacion")]
    public DateTime FechaCreacion { get; set; }

    [Column("fecha_asignacion")]
    public DateTime? FechaAsignacion { get; set; }

    [Column("fecha_aceptacion")]
    public DateTime? FechaAceptacion { get; set; }

    [Column("fecha_surtido")]
    public DateTime? FechaSurtido { get; set; }

    [Column("fecha_entrega")]
    public DateTime? FechaEntrega { get; set; }

    [Column("fecha_ultima_actualizacion")]
    public DateTime FechaUltimaActualizacion { get; set; }

    [InverseProperty("Pedido")]
    public virtual ICollection<CanalPedido> CanalPedido { get; set; } = new List<CanalPedido>();

    [ForeignKey("CanalVentaId")]
    [InverseProperty("Pedido")]
    public virtual CanalVenta CanalVenta { get; set; }

    [InverseProperty("Pedido")]
    public virtual ICollection<CarrierAsignado> CarrierAsignado { get; set; } = new List<CarrierAsignado>();

    [ForeignKey("CarrierFinalId")]
    [InverseProperty("Pedido")]
    public virtual CarrierCatalogo CarrierFinal { get; set; }

    [ForeignKey("ClienteId")]
    [InverseProperty("Pedido")]
    public virtual Cliente Cliente { get; set; }

    [InverseProperty("Pedido")]
    public virtual ICollection<ConfirmacionPago> ConfirmacionPago { get; set; } = new List<ConfirmacionPago>();

    [InverseProperty("Pedido")]
    public virtual ICollection<Devolucion> Devolucion { get; set; } = new List<Devolucion>();

    [ForeignKey("DireccionEnvioId")]
    [InverseProperty("Pedido")]
    public virtual DireccionEnvio DireccionEnvio { get; set; }

    [ForeignKey("EstatusActualId")]
    [InverseProperty("Pedido")]
    public virtual EstatusPedido EstatusActual { get; set; }

    [InverseProperty("Pedido")]
    public virtual ICollection<HistoricoEstatusPedido> HistoricoEstatusPedido { get; set; } = new List<HistoricoEstatusPedido>();

    [InverseProperty("Pedido")]
    public virtual ICollection<HistoricoSendEmail> HistoricoSendEmail { get; set; } = new List<HistoricoSendEmail>();

    [InverseProperty("Pedido")]
    public virtual ICollection<HistoricoTrackingEnvio> HistoricoTrackingEnvio { get; set; } = new List<HistoricoTrackingEnvio>();

    [InverseProperty("Pedido")]
    public virtual ICollection<IntegrationAlerts> IntegrationAlerts { get; set; } = new List<IntegrationAlerts>();

    [InverseProperty("Pedido")]
    public virtual ICollection<OutboxEvents> OutboxEvents { get; set; } = new List<OutboxEvents>();

    [InverseProperty("Pedido")]
    public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; } = new List<PedidoDetalle>();

    [InverseProperty("Pedido")]
    public virtual ICollection<WebhookEventsLog> WebhookEventsLog { get; set; } = new List<WebhookEventsLog>();
}