// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

public partial class TipoServicio
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("servicio")]
    [StringLength(100)]
    public string Servicio { get; set; }

    [InverseProperty("TipoServicio")]
    public virtual ICollection<CarrierSla> CarrierSla { get; set; } = new List<CarrierSla>();
}