// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Index("EstatusOrigenId", "EstatusDestinoId", Name = "UQ_Transicion_Origen_Destino", IsUnique = true)]
public partial class TransicionEstatusConfig
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("estatus_origen_id")]
    public Guid EstatusOrigenId { get; set; }

    [Column("estatus_destino_id")]
    public Guid EstatusDestinoId { get; set; }

    [Column("activo")]
    public bool Activo { get; set; }

    [ForeignKey("EstatusDestinoId")]
    [InverseProperty("TransicionEstatusConfigEstatusDestino")]
    public virtual EstatusPedido EstatusDestino { get; set; }

    [ForeignKey("EstatusOrigenId")]
    [InverseProperty("TransicionEstatusConfigEstatusOrigen")]
    public virtual EstatusPedido EstatusOrigen { get; set; }
}