// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GncOmsApi.Models;

[Table("webhook_events_log")]
[Index("CarrierId", Name = "IX_webhook_events_log_carrier_id")]
[Index("PedidoId", Name = "IX_webhook_events_log_pedido_id")]
public partial class WebhookEventsLog
{
    [Key]
    [Column("webhook_id")]
    [StringLength(100)]
    public string WebhookId { get; set; }

    [Column("pedido_id")]
    public Guid PedidoId { get; set; }

    [Column("carrier_id")]
    public Guid CarrierId { get; set; }

    [Required]
    [Column("event_type")]
    [StringLength(100)]
    public string EventType { get; set; }

    [Column("received_at")]
    public DateTime ReceivedAt { get; set; }

    [Column("procesado")]
    public bool Procesado { get; set; }

    [ForeignKey("CarrierId")]
    [InverseProperty("WebhookEventsLog")]
    public virtual CarrierCatalogo Carrier { get; set; }

    [ForeignKey("PedidoId")]
    [InverseProperty("WebhookEventsLog")]
    public virtual Pedido Pedido { get; set; }
}